/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CTSSettings;

/**
 *
 * @author Melike Geçer
 */
public class CTSSettingsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CTSSettingsJPanel
     */
    public CTSSettingsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeVoiceRadioButtonGroup = new javax.swing.ButtonGroup();
        enablePanel = new javax.swing.JPanel();
        enableLabel = new javax.swing.JLabel();
        enableCheckbox = new javax.swing.JCheckBox();
        changeVoicePanel = new javax.swing.JPanel();
        changeVoiceLabel = new javax.swing.JLabel();
        voicesPanel = new javax.swing.JPanel();
        femaleVoiceRadioButton = new javax.swing.JRadioButton();
        maleVoiceRadioButton1 = new javax.swing.JRadioButton();
        maleVoiceRadioButton2 = new javax.swing.JRadioButton();
        developerLabel = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        enablePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(enableLabel, org.openide.util.NbBundle.getMessage(CTSSettingsJPanel.class, "CTSSettingsJPanel.enableLabel.text")); // NOI18N
        enablePanel.add(enableLabel);

        org.openide.awt.Mnemonics.setLocalizedText(enableCheckbox, org.openide.util.NbBundle.getMessage(CTSSettingsJPanel.class, "CTSSettingsJPanel.enableCheckbox.text")); // NOI18N
        enablePanel.add(enableCheckbox);

        add(enablePanel);

        changeVoicePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(changeVoiceLabel, org.openide.util.NbBundle.getMessage(CTSSettingsJPanel.class, "CTSSettingsJPanel.changeVoiceLabel.text")); // NOI18N
        changeVoicePanel.add(changeVoiceLabel);

        voicesPanel.setLayout(new javax.swing.BoxLayout(voicesPanel, javax.swing.BoxLayout.PAGE_AXIS));

        changeVoiceRadioButtonGroup.add(femaleVoiceRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(femaleVoiceRadioButton, org.openide.util.NbBundle.getMessage(CTSSettingsJPanel.class, "CTSSettingsJPanel.femaleVoiceRadioButton.text")); // NOI18N
        voicesPanel.add(femaleVoiceRadioButton);

        changeVoiceRadioButtonGroup.add(maleVoiceRadioButton1);
        org.openide.awt.Mnemonics.setLocalizedText(maleVoiceRadioButton1, org.openide.util.NbBundle.getMessage(CTSSettingsJPanel.class, "CTSSettingsJPanel.maleVoiceRadioButton1.text")); // NOI18N
        voicesPanel.add(maleVoiceRadioButton1);

        changeVoiceRadioButtonGroup.add(maleVoiceRadioButton2);
        org.openide.awt.Mnemonics.setLocalizedText(maleVoiceRadioButton2, org.openide.util.NbBundle.getMessage(CTSSettingsJPanel.class, "CTSSettingsJPanel.maleVoiceRadioButton2.text")); // NOI18N
        voicesPanel.add(maleVoiceRadioButton2);

        changeVoicePanel.add(voicesPanel);

        add(changeVoicePanel);

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(developerLabel, org.openide.util.NbBundle.getMessage(CTSSettingsJPanel.class, "CTSSettingsJPanel.developerLabel.text")); // NOI18N
        developerLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        developerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        developerLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(developerLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeVoiceLabel;
    private javax.swing.JPanel changeVoicePanel;
    private javax.swing.ButtonGroup changeVoiceRadioButtonGroup;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JCheckBox enableCheckbox;
    private javax.swing.JLabel enableLabel;
    private javax.swing.JPanel enablePanel;
    private javax.swing.JRadioButton femaleVoiceRadioButton;
    private javax.swing.JRadioButton maleVoiceRadioButton1;
    private javax.swing.JRadioButton maleVoiceRadioButton2;
    private javax.swing.JPanel voicesPanel;
    // End of variables declaration//GEN-END:variables
}
